### ISSUE TITLE
Cannot access ErrorReporter before ACRA#init

### ISSUE THREAD

**Issue by ligi** [AndlyticsProject/andlytics#694]
in v 2.7.2:
```
E/AndroidRuntime(11392): java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
E/AndroidRuntime(11392): 	at org.acra.ACRA.getErrorReporter(ACRA.java:221)
E/AndroidRuntime(11392): 	at com.github.andlyticsproject.BaseActivity.sendAracReport(BaseActivity.java:232)
E/AndroidRuntime(11392): 	at com.github.andlyticsproject.BaseActivity.access$000(BaseActivity.java:35)
E/AndroidRuntime(11392): 	at com.github.andlyticsproject.BaseActivity$5$1.run(BaseActivity.java:251)
E/AndroidRuntime(11392): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(11392): 	at com.github.andlyticsproject.BaseActivity$5.onClick(BaseActivity.java:254)
E/AndroidRuntime(11392): 	at com.github.andlyticsproject.dialog.CrashDialog$CrashDialogBuilder$1.onClick(CrashDialog.java:168)
E/AndroidRuntime(11392): 	at android.view.View.performClick(View.java:5191)
E/AndroidRuntime(11392): 	at android.view.View$PerformClick.run(View.java:20916)
E/AndroidRuntime(11392): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(11392): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(11392): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(11392): 	at android.app.ActivityThread.main(ActivityThread.java:5944)
E/AndroidRuntime(11392): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11392): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11392): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(11392): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by mars3142** [comment]
I've got more logcat entries:

    W/ACRA : Error :
    org.acra.ACRAConfigurationException: TOAST mode: you have to define the resToastText parameter in your application @ReportsCrashes() annotation.
            at org.acra.ACRA.checkCrashResources(ACRA.java:259)
            at org.acra.ACRA.init(ACRA.java:171)
            at org.acra.ACRA.init(ACRA.java:135)
            at org.acra.ACRA.init(ACRA.java:120)
            at com.github.andlyticsproject.AndlyticsApp.initAcra(AndlyticsApp.java:48)
            at com.github.andlyticsproject.AndlyticsApp.onCreate(AndlyticsApp.java:31)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    W/AndlyticsApp : ACRA.init() called more than once?: Cannot access ErrorReporter before ACRA#init
    java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
            at org.acra.ACRA.getErrorReporter(ACRA.java:221)
            at com.github.andlyticsproject.AndlyticsApp.initAcra(AndlyticsApp.java:52)
            at com.github.andlyticsproject.AndlyticsApp.onCreate(AndlyticsApp.java:31)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
