### ISSUE TITLE
OutOfMemoryError while decoding bitmap in home screen (a LOT of apps in the list)

### ISSUE THREAD

**Issue by mmathieum** [AndlyticsProject/andlytics#704]
Andlytics app version 2.7.3 from Google Play Store.
(I'm in the testing program with the G+ community)

Issue on Nexus 7 (2012) running Android 4.4.4.
(no problem with same account on a Nexus 5 running Android 5.1.1)

```java
 java.lang.RuntimeException: An error occured while executing doInBackground()
      at android.os.AsyncTask$3.done(AsyncTask.java:300)
      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:841)
  Caused by: java.lang.OutOfMemoryError
      at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
      at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:620)
      at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
      at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:376)
      at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
      at com.github.andlyticsproject.MainListAdapter$GetCachedImageTask.doInBackground(MainListAdapter.java:714)
      at com.github.andlyticsproject.MainListAdapter$GetCachedImageTask.doInBackground(MainListAdapter.java:683)
      at android.os.AsyncTask$2.call(AsyncTask.java:288)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      ... 4 more
```

**Comment by willlunniss** [comment]
How many apps?

**Comment by mmathieum** [comment]
95 apps currently

**Comment by willlunniss** [comment]
Can you have a look with the memory analyser to see where it is all going, it may be that its from loading all the app data from the DB, and the image simply hits the upper limit.
