### ISSUE TITLE
App not work anymore May 21st 2016

### ISSUE THREAD

**Issue by dzungpv** [AndlyticsProject/andlytics#731]
Google updated Play Store console and break the app, they also publish Google Play console app but the feature far from andlytics. I see they have some api access in Console, but i don't know if andlytics can use those api instead of hack.

**Comment by rchugunov** [comment]
It seems that they forbidded api used in this app

**Comment by willlunniss** [comment]
Seems to still work for me. What error are you getting (logcat), and can you try the ```dev``` version?

**Comment by willlunniss** [comment]
I've fixed the comment fetching in ```master``` and ```dev```, are there any other issues? Can someone give it a test please?

**Comment by Pyro979** [comment]
@willlunniss, are you pushing fix via beta or do we need to build the whole thing?

**Comment by nelenkov** [comment]
dev seems to work fine, including loading comments. The material version seems quite stable, we should probably release that to the beta channel, as well

**Comment by willlunniss** [comment]
@Pyro979 You'll have to build it yourself for now. 

Yes I have been using it for a while now and haven't had any issues. I should have time to do the release tonight (UK time), unless you are free to do it sooner.

**Comment by nelenkov** [comment]
I've pushed master as v2.7.5 and dev as v2.8.0-BETA. Should show up shortly.

**Comment by dzungpv** [comment]
Great @nelenkov @willlunniss , I am waiting it on Play store.

**Comment by Pyro979** [comment]
@nelenkov @willlunniss comments look good. There is a few minor issues I noticed in beta. Does beta feedback go into issues?

**Comment by nelenkov** [comment]
Pull requests for beta go to the dev branch :)

**Comment by rchugunov** [comment]
Ok guys I attach some stacktrace from logcat (version from Google Play)
```

05-25 16:13:45.469 13360-13635/? E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:376)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:206)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
                                         android.os.AsyncTask$2.call(AsyncTask.java:295)
                                         java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                         java.lang.Thread.run(Thread.java:818)
                                         org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:76)
                                         org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:63)
                                         org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:965)
                                         org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:935)
                                         org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:924)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:370)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:206)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
                                         android.os.AsyncTask$2.call(AsyncTask.java:295)
                                         java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                         java.lang.Thread.run(Thread.java:818)
05-25 16:13:45.481 13360-13635/? E/Main: Error while requesting developer console : Status-Code: 403
                                         com.github.andlyticsproject.console.NetworkException: Status-Code: 403
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:376)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:206)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                             at java.lang.Thread.run(Thread.java:818)
                                          Caused by: org.apache.http.client.HttpResponseException: Forbidden
                                             at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:76)
                                             at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:63)
                                             at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:965)
                                             at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:935)
                                             at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:924)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:370)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:206) 
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113) 
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101) 
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521) 
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488) 
                                             at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                             at java.lang.Thread.run(Thread.java:818) 
```

App shows a toast "There are no published apps" and "Network error". I have published apps on the selected account

**Comment by nelenkov** [comment]
This is an authentication error, log in to the Web console, and check if there are any warnings, etc. (confirm phone, 2FA, etc.) associated with your account.

**Comment by rchugunov** [comment]
You mean Play Developer Console? No warnings are there

**Comment by willlunniss** [comment]
@nelenkov Thanks for doing the release.
