### ISSUE TITLE
Anyone else getting errors today?

### ISSUE THREAD

**Issue by casolorz** [AndlyticsProject/andlytics#743]
I'm getting the dialog that says there was an error and send report. 
Anyone else?

**Comment by udiidan** [comment]
Yes, same here.

**Comment by udiidan** [comment]
Not sure, but the logcat shows it's auth related:

> 04-12 21:19:11.729 32066-32347/com.github.andlyticsproject E/Main: Error while requesting developer console : Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                   com.github.andlyticsproject.console.AuthenticationException: Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by casolorz** [comment]
@udiidan have you had it running before? Because I was getting that error a few weeks ago when trying to run my own copy, see issue #740

**Comment by udiidan** [comment]
I've seen this exception after running the project from Android Studio. I don't know if the exception before was different, I guess we'll need the input of others who will encounter this.

**Comment by Farasy** [comment]
Report sent

**Comment by dieterthiess** [comment]
Here is my stacktrace;

`Error while requesting developer console : com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:166)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
                                                                 android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                 java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                 java.lang.Thread.run(Thread.java:841)
                                                                 org.json.JSONObject.get(JSONObject.java:354)
                                                                 org.json.JSONObject.getInt(JSONObject.java:443)
                                                                 com.github.andlyticsproject.console.v2.JsonParser.parseAppInfos(JsonParser.java:292)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:163)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
                                                                 android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                 java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                 java.lang.Thread.run(Thread.java:841)`

**Comment by dzungpv** [comment]
Google may change their interface so the app stop working, it need some fix.
Now Google have their own app but it not include features like Andlytics.

**Comment by XdebugX** [comment]
Any idea when an update for this?

**Comment by AlexVPerl** [comment]
I too would love to see an update/fix for this. Google's own Console app isn't nearly as good.

**Comment by magnusgronbek** [comment]
Please fix this. I use this app daily, it's a really good app.

**Comment by nelenkov** [comment]
looks like the activeInstalls field has been removed. IIRC this was announced a while ago. 
A proper fix would require updating the UI, but for now it works if we just set it to 0.

**Comment by nelenkov** [comment]
And really, the app is open source, so anyone could've spotted and commited a fix for this...

**Comment by casolorz** [comment]
I tried to get it running on my end but never could get it to work, #740. Sounded like someone else here had the same issue.

**Comment by magnusgronbek** [comment]
I also tied to get it running in Android Studio but can't get it to work. I get invalid_scope when trying to get token. Any ideas to get it running nalenkov?

**Comment by casolorz** [comment]
Just got the update. It is working well again.

**Comment by XdebugX** [comment]
It's working again for me, thanks. I would suggest replacing active installs with Googles new metric "Installs on active devices."
