### ISSUE TITLE
Unable to fetch data from account.

### ISSUE THREAD

**Issue by 5hivams** [AndlyticsProject/andlytics#746]
I just downloaded your project and ran in studio, After signing account I got blank screen with bellow error in background log:

DeveloperAccountManager: Set to SELECTED: DeveloperAccount [name=cogitatesolution@gmail.com, developerId=null, state=SELECTED]
05-05 19:32:06.409 28079-28210/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.a(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getTokenWithNotification(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:106)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateSilently(OauthAccountManagerAuthenticator.java:77)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.performSync(SyncAdapterService.java:93)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.access$000(SyncAdapterService.java:34)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService$SyncAdapterImpl.onPerformSync(SyncAdapterService.java:64)
                                                                                                   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-05 19:32:07.134 28079-28210/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.a(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getTokenWithNotification(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:106)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateSilently(OauthAccountManagerAuthenticator.java:77)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.performSync(SyncAdapterService.java:93)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.access$000(SyncAdapterService.java:34)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService$SyncAdapterImpl.onPerformSync(SyncAdapterService.java:64)
                                                                                                   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-05 19:32:07.135 28079-28210/com.github.andlyticsproject E/SyncAdapterService: error during dev console stats sync
                                                                                 com.github.andlyticsproject.console.AuthenticationException: Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                                     at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:116)
                                                                                     at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateSilently(OauthAccountManagerAuthenticator.java:77)
                                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                     at com.github.andlyticsproject.sync.SyncAdapterService.performSync(SyncAdapterService.java:93)
                                                                                     at com.github.andlyticsproject.sync.SyncAdapterService.access$000(SyncAdapterService.java:34)
                                                                                     at com.github.andlyticsproject.sync.SyncAdapterService$SyncAdapterImpl.onPerformSync(SyncAdapterService.java:64)
                                                                                     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-05 19:32:07.867 28079-28216/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:123)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
05-05 19:32:08.613 28079-28216/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:123)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
05-05 19:32:08.613 28079-28216/com.github.andlyticsproject E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                   com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                   android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                   java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   java.lang.Thread.run(Thread.java:818)
05-05 19:32:08.641 28079-28216/com.github.andlyticsproject E/Main: Error while requesting developer console : Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                   com.github.andlyticsproject.console.AuthenticationException: Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
05-05 19:32:08.738 28079-28147/com.github.andlyticsproject V/RenderScript: 0x9fa9c000 Launching thread(s), CPUs 4
05-05 19:32:09.410 28079-28241/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.a(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getTokenWithNotification(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:106)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateSilently(OauthAccountManagerAuthenticator.java:77)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.performSync(SyncAdapterService.java:93)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.access$000(SyncAdapterService.java:34)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService$SyncAdapterImpl.onPerformSync(SyncAdapterService.java:64)
                                                                                                   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-05 19:32:10.158 28079-28241/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.a(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getTokenWithNotification(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:106)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateSilently(OauthAccountManagerAuthenticator.java:77)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.performSync(SyncAdapterService.java:93)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService.access$000(SyncAdapterService.java:34)
                                                                                                   at com.github.andlyticsproject.sync.SyncAdapterService$SyncAdapterImpl.onPerformSync(SyncAdapterService.java:64)
                                                                                                   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-05 19:32:10.158 28079-28241/com.github.andlyticsproject E/SyncAdapterService: error during dev console stats sync
                                                                                 com.github.andlyticsproject.console.AuthenticationException: Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                                     at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:116)
                                                                                     at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateSilently(OauthAccountManagerAuthenticator.java:77)
                                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                     at com.github.andlyticsproject.sync.SyncAdapterService.performSync(SyncAdapterService.java:93)
                                                                                     at com.github.andlyticsproject.sync.SyncAdapterService.access$000(SyncAdapterService.java:34)
                                                                                     at com.github.andlyticsproject.sync.SyncAdapterService$SyncAdapterImpl.onPerformSync(SyncAdapterService.java:64)
                                                                                     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-05 19:36:27.511 28079-28209/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:123)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
05-05 19:36:28.242 28079-28209/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:123)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
05-05 19:36:28.243 28079-28209/com.github.andlyticsproject E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                   com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                   android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                   java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   java.lang.Thread.run(Thread.java:818)
05-05 19:36:28.243 28079-28209/com.github.andlyticsproject E/Main: Error while requesting developer console : Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                   com.github.andlyticsproject.console.AuthenticationException: Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
05-05 19:37:13.715 28079-28216/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:123)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
05-05 19:37:14.438 28079-28216/com.github.andlyticsproject E/OauthAccountManagerAuthenticator: Unrecoverable authentication exception: UNREGISTERED_ON_API_CONSOLE
                                                                                               com.google.android.gms.auth.GoogleAuthException: UNREGISTERED_ON_API_CONSOLE
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:123)
                                                                                                   at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                                                   at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                                                   at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
05-05 19:37:14.439 28079-28216/com.github.andlyticsproject E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                   com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                   android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                   java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   java.lang.Thread.run(Thread.java:818)
05-05 19:37:14.439 28079-28216/com.github.andlyticsproject E/Main: Error while requesting developer console : Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                   com.github.andlyticsproject.console.AuthenticationException: Authentication error: UNREGISTERED_ON_API_CONSOLE
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:139)
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
05-05 19:42:01.103 28079-32431/com.github.andlyticsproject W/OauthAccountManagerAuthenticator: transient error encountered: NetworkError
05-05 19:42:01.104 28079-32431/com.github.andlyticsproject E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:142)
                                                                   com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                   com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                   com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                   android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                   java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   java.lang.Thread.run(Thread.java:818)
05-05 19:42:01.104 28079-32431/com.github.andlyticsproject E/Main: Error while requesting developer console : NetworkError
                                                                   com.github.andlyticsproject.console.NetworkException: NetworkError
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:142)
                                                                       at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateWithCachedCredentialas(DevConsoleV2.java:324)
                                                                       at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:97)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                       at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by nelenkov** [comment]
Try registering your app in the Google API console, see README.
Note that doesn't appear to work for everyone, not 100% sure about the reason.
