### ISSUE TITLE
Unable to parse again "No value for 8"

### ISSUE THREAD

**Issue by casolorz** [AndlyticsProject/andlytics#749]
6-28 11:27:01.466 9710-20573/? E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:166)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                        com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                        com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                        android.os.AsyncTask$2.call(AsyncTask.java:305)
                                        java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                        java.lang.Thread.run(Thread.java:761)
                                        org.json.JSONObject.get(JSONObject.java:389)
                                        org.json.JSONObject.getLong(JSONObject.java:514)
                                        com.github.andlyticsproject.console.v2.JsonParser.parseAppInfos(JsonParser.java:249)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:163)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                        com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                        com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                        com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                        android.os.AsyncTask$2.call(AsyncTask.java:305)
                                        java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                        java.lang.Thread.run(Thread.java:761)
06-28 11:27:01.467 9710-20573/? E/Main: Error while requesting developer console : {"result":{"1":[{"1":{"1":"mypackage","2":{"1":[{"2":"My App Name"}]},"7":1,"11":{"3":"1421234565431"},"17":"4973123434212332221"},"4":true,"6":{"1":"My App Name","3":"https://imageurl","7":false}},{"1":{"1":"mypackage","2":{"1":[{"2":"app name"}]},"7":2,"11":{"3":"1425123343321"},"17":"4973201234556632493"},"4":true,"6":{"1":"app name","3":"https://imageurl"}},{"1":{"1":"mypacakge","2":{"1":[{"2":"My App Name"}]},"7":1,"11":{"3":"1498123445568"},"17":"4912233444333222231"},"4":true,"6":{"1":"My App Name","3":"https://imageurl","7":false}}]},"xsrf":"AMtNNDFG7asdsasdasdasdasbv4FADXzxEkg:1498123123210"}
                                        com.github.andlyticsproject.console.DevConsoleProtocolException: {"result":{"1":[{"1":{"1":"mypackage","2":{"1":[{"2":"My App Name"}]},"7":1,"11":{"3":"1421234565431"},"17":"4973123434212332221"},"4":true,"6":{"1":"My App Name","3":"https://imageurl","7":false}},{"1":{"1":"mypackage","2":{"1":[{"2":"app name"}]},"7":2,"11":{"3":"1425123343321"},"17":"4973201234556632493"},"4":true,"6":{"1":"app name","3":"https://imageurl"}},{"1":{"1":"mypacakge","2":{"1":[{"2":"My App Name"}]},"7":1,"11":{"3":"1498123445568"},"17":"4912233444333222231"},"4":true,"6":{"1":"My App Name","3":"https://imageurl","7":false}}]},"xsrf":"AMtNNDFG7asdsasdasdasdasbv4FADXzxEkg:1498123123210"}
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:166)
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                            at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                            at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                            at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                            at java.lang.Thread.run(Thread.java:761)
                                         Caused by: org.json.JSONException: No value for 8
                                            at org.json.JSONObject.get(JSONObject.java:389)
                                            at org.json.JSONObject.getLong(JSONObject.java:514)
                                            at com.github.andlyticsproject.console.v2.JsonParser.parseAppInfos(JsonParser.java:249)
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:163)
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210) 
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113) 
                                            at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101) 
                                            at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558) 
                                            at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525) 
                                            at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                            at java.lang.Thread.run(Thread.java:761)

**Comment by nelenkov** [comment]
Updated and pushed a release. Not sure I can keep this up though...

**Comment by casolorz** [comment]
Thank you, I really appreciate it. Would you consider allowing other people to join the project? I use this app every day and I feel like I'm flying blind when it doesn't work.

**Comment by nelenkov** [comment]
If you promise to do maintenance releases, sure :) 
We have to ask @AndyScherzinger to give you access to the Play Console, and I can send you the private key.

**Comment by casolorz** [comment]
Yeah I think I could work on simple maintenance releases.
