### ISSUE TITLE
Broke again

### ISSUE THREAD

**Issue by casolorz** [AndlyticsProject/andlytics#750]
Got this exception. My offer to help with the project by fixing bugs or even donating money still stands. 

07-26 11:37:35.947 25089-25811/? E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:166)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                         android.os.AsyncTask$2.call(AsyncTask.java:305)
                                         java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                         java.lang.Thread.run(Thread.java:761)
                                         org.json.JSONObject.get(JSONObject.java:389)
                                         org.json.JSONObject.getJSONObject(JSONObject.java:609)
                                         com.github.andlyticsproject.console.v2.JsonParser.parseAppInfos(JsonParser.java:141)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:163)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                         com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                         com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                         android.os.AsyncTask$2.call(AsyncTask.java:305)
                                         java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                         java.lang.Thread.run(Thread.java:761)
07-26 11:37:35.947 25089-25811/? E/Main: Error while requesting developer console : {"error":{"code":736569013,"data":{"1":736569013}}}
                                         com.github.andlyticsproject.console.DevConsoleProtocolException: {"error":{"code":736569013,"data":{"1":736569013}}}
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:166)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                             at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                             at java.lang.Thread.run(Thread.java:761)
                                          Caused by: org.json.JSONException: No value for result
                                             at org.json.JSONObject.get(JSONObject.java:389)
                                             at org.json.JSONObject.getJSONObject(JSONObject.java:609)
                                             at com.github.andlyticsproject.console.v2.JsonParser.parseAppInfos(JsonParser.java:141)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfosResponse(DevConsoleV2Protocol.java:163)
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:210) 
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113) 
                                             at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101) 
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558) 
                                             at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525) 
                                             at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                             at java.lang.Thread.run(Thread.java:761)

**Comment by nelenkov** [comment]
Send me your Dropbox account to my <first name.last name> @ gmail, and I'll share the signing key, so you can build and test

**Comment by casolorz** [comment]
Hope I sent it to the right gmail account :)

**Comment by casolorz** [comment]
Found a simple fix 
https://github.com/casolorz/andlytics/commit/6e2f475aec0fc5d6f029ef1e46316c06608b9cb6

I'm assuming you don't want my modified gradle file on the pull request?

**Comment by magnusgronbek** [comment]
Have you mamaged to run your own copy of the app, casolorz?

**Comment by casolorz** [comment]
@magnusgronbek yes but I've started attempting to contribute to the project so I got the keys.

**Comment by magnusgronbek** [comment]
So you still get invalid_scope when using your own keys?

**Comment by casolorz** [comment]
Yeah.

**Comment by nelenkov** [comment]
@casolorz Can you bump the version, add a line to changelog and submit a pull request?
See https://github.com/AndlyticsProject/andlytics/wiki/Release-Procedure

Not sure about the build config, but if using the release key to debug is to only way to run it, I guess we need that change.

**Comment by casolorz** [comment]
I did steps 1 and 2 and submitted the pull request. Did you want me to do the rest of the steps?

**Comment by nelenkov** [comment]
Thanks, I built and pushed to Play Store.
