### ISSUE TITLE
Error while requesting developer console : Status-Code: 403

### ISSUE THREAD

**Issue by dieterthiess** [AndlyticsProject/andlytics#753]
With today's update i get an error when i try to load:

`07-28 04:55:56.648 4016-4059/com.github.andlyticsproject E/Main: Error while requesting developer console : com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:376)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:237)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                 android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                 java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 java.lang.Thread.run(Thread.java:818)
                                                                 org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:76)
                                                                 org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:63)
                                                                 org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:662)
                                                                 org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:632)
                                                                 org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:621)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:370)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:237)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                                                 com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                 com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                 android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                 java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 java.lang.Thread.run(Thread.java:818)
07-28 04:55:56.648 4016-4059/com.github.andlyticsproject E/Main: Error while requesting developer console : Status-Code: 403
                                                                 com.github.andlyticsproject.console.NetworkException: Status-Code: 403
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:376)
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:237)
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113)
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101)
                                                                     at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558)
                                                                     at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: org.apache.http.client.HttpResponseException: Forbidden
                                                                     at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:76)
                                                                     at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:63)
                                                                     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:662)
                                                                     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:632)
                                                                     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:621)
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:370)
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:237) 
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:113) 
                                                                     at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:101) 
                                                                     at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:558) 
                                                                     at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:525) 
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) `

**Comment by dieterthiess** [comment]
I was able to investigate a bit more about the reason for this problem. 
I have permissions for other play consoles in my account, but only for selected apps of these accounts. I found out, that when the visibility permission is not granted globally, but only for a selected app, the error above will occur. With the global visibility permission, everything is fine. 
Before the recent api changes and update, this was working. Maybe it could be an option not to skip when a 403 occurs, but continue with the next one? 

Dieter
